server:
  port: 1119

#Eureka
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}
    instanceId: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://registry-center:1111/eureka/

spring:
  application:
    name: config-center
  cloud:
    bus:
      refresh:
        enabled: true
    config:
      server:
        git:
          uri: https://github.com/Cnt-x-y/config-center.git
          #username: 2260387897@qq.com
          #password:
          search-paths: /**
          force-pull: true
  rabbitmq:
    host: 192.168.0.178
    port: 5672
    username: xtt
    password: 123456
    virtualHost: xiaopangche

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh
      cors:
        allowed-origins: "*"
        llowed-methods: "*"